### PR TITLE
noob fix for hgetall returns Array, fixes #4

### LINKED ISSUE #4: hgetall returns Array
`hgetall` should return a Hash instead
(referring to [redis-documentation](http://redis.io/topics/data-types-intro#hashes))

### PR DESCRIPTION
**Pull request by ukd1**
...this is my first PR in crystal. It's probably shit, but works. I'd love feedback or pointers :+1: 

(I tired to make the array -> hash more nicely, but couldn't figure it out!)

### CODE REVIEW

**Comment by stefanwille** [comment]
Hi Ukd1,

thank you for the PR!

The reason why the current behaviour is the way it is, is that that a future should return the same type as the direct execution. For instance,

```
redis.hgetall("myhash").should eq({"a" => "123", "b" => "456"})
```

and

```
futures = [] of Redis::Future
results = redis.pipelined do |pipeline|
            futures << pipeline.hgetall("myhash")
          end
results[0].should eq({"a" => "123", "b" => "456"})
futures[0].value.should eq({"a" => "123", "b" => "456"})
```

With your PR, this would not hold true - the future would still return an array.
To fix this is a bit tricky, which is why I haven't done it so far.

**Comment by stefanwille** [comment]
Maybe this was not 100% clear. I am talking about this assertion from the second example:

```
futures[0].value.should eq({"a" => "123", "b" => "456"})
```

which would not be satisfied by your PR.

**Comment by ukd1** [comment]
@stefanwille ok, thanks - is that fixable?

Also, is there a better way of array -> hash which I've missed?

**Comment by stefanwille** [comment]
@ukd1 my idea to handle this is to pass the conversion from a RedisValue result to the desired type as a proc or block. 

In the example of  `hgetall`, it would be something like this in `commands.cr`:

```crystal
def hgetall(key)
    symbol_to_string_hash_command(["HGETALL", key.to_s], ->convert_to_string_hash) 
end

def convert_to_string_hash(x : Array(RedisValue))
  y = {} of String => String
  x.each_with_index do |v, i|
    if i.odd?
      y[x[i-1]] = v
    end
  end
  
  y
end
```

Then this conversion proc can be stored by the strategies in redis/strategy (such as pipeline.cr) and be used to convert the result object to the right type once the result is available.

I expect the hard part is to get the types right in all the cases.

**Comment by stefanwille** [comment]
@ukd1 I haven't seen a nice way to build an array from a hash. But you can make the iteration nicer by using [Number#step](http://crystal-lang.org/api/Number.html#step%28limit%3D%3Cspanclass%3D%22n%22%3Enil%3C%2Fspan%3E%2Cby%3D%3Cspanclass%3D%22n%22%3E1%3C%2Fspan%3E%2C%26block%29-instance-method):

```crystal
def convert_string_array_to_hash(x : Array(RedisValue))
  y = {} of RedisValue => RedisValue
  0.step(by: 2, limit: x.size) do |i|
      y[x[i]] = x[i+1]
  end
  
  y
end
```

**Comment by ukd1** [comment]
@stefanwille been AFK for a bit...let me fix!

**Comment by stefanwille** [comment]
Sure :smile:

**Comment by stefanwille** [comment]
I am closing this PR since there was no follow up to make it work with futures.

**Pull request closed without merging**
