### PR TITLE
Optimization: don't create temporary strings when marshalling, just write directly to the IO

### PR DESCRIPTION
**Pull request by asterite**
First of all, I really like your Redis client :-) 

I actually started writing one [here](http://github.com/manastech/crystal_redis) some time ago for a basic app that I wrote, but I just did the basics. Plus, I don't know well the Redis protocol, the pipeline mode and all of the strategies, so it's really good that you started from scratch and modelled everything very well. Having top-quality libraries, with good documentation, like yours, helps Crystal a lot. Thank you! I'll soon erase the other project as yours is by far superior ;-)

This pull request optimizes the IO logic. One rule of thumb for making efficient code is not creating temporary short-lived objects. IO in Crystal is optimized for that case. For example, instead of having just a `#to_s` method, types have a `#to_s(IO)` method to write directly to an IO. This makes it possible to, for example, output a number to a console without allocating any memory. This isn't possible in most of the other languages out there.

With this small optimization (small in code size ;-)) I went from 297933 operations per second to 484958, in pipeline mode.

(As a side note, instead of documenting return types in the docs, you can use return types, for example:

```crystal
# Not so good:

# Returns an Int32
def foo
  1
end

# Better:

# the code speaks for itself
def foo : Int32
end
```

This feature was added in 0.7.0 so don't worry if you didn't know about it. It's also not documented anywhere yet, but hopefully I'll finish the docs this week or the next one)

### CODE REVIEW

**Comment by asterite** [comment]
Oh, one more thing. I see that for commands you use Array all the times. Arrays also allocate. If you'd use tuples I'm sure you can get even better performance from your library. But you won't be able to use tuples the whole time.

**Comment by asterite** [comment]
Don't worry about tuples, I just checked the code better and it's not always possible to use them. For example the "set" comamnd has many options, so that needs an Array. In any case, I think the performance of this library is already quite good :-)

**Comment by asterite** [comment]
@stefanwille So now this library if faster than the C library? :open_mouth:  How can that be? :-)

**Comment by stefanwille** [comment]
Hello Ary,

thank you so much for your kind words!!! I really appreciate it!

And thanks a lot for the pull request! It makes a big difference indeed!!  I have updated the README accordingly, the improvement is amazing :smiley:

About declaring the return types: I am glad to see that this feature is in Crystal now. With the crystal-redis library I think am not able to use it, because each Redis command method may either return a concrete type such Int64 or a Future. I take advantage of Crystal's global type interference to make this happen. For example, Redis#get returns a String, and PipelineApi#get returns a Future. I have no good idea how to avoid this trick and be able to declare return types. It would be cool though. I tried it a little, and the documentation looked definitely better. Maybe you have an idea.

Regarding tuples: After your message I tried to support tuples in side by side with arrays, but I didn't get a measurable speedup. Maybe that's because I used a union type (Array(RedisValue) | Tuple) to represent requests.

**Comment by stefanwille** [comment]
@asterite About this library being faster than C: It seems to me that Hiredis doesn't perform so well.

I learned some Go over the weekend and tried two Redis libraries, Radix and Redigo. Radix performs 90.000 commands per second, BUT Redigo 640.000 commands per second! This is much faster than C with Hiredis.

My assumption is that Hiredis gets outperformed because it uses a sprintf style API. I want to try another C based library to verify this.

**Comment by asterite** [comment]
@stefanwille Hi again :-)

About the return types: there's no need to always put theme, so the way you did it is fine.
About tuples: you are right, the performance doesn't change.

However, I still wondered why it's slower than Redigo (because I'm a performance freak :-P). Turns out out BufferedIO wasn't really good at writing things: it just kept a StringIO internally and let it grow until you invoked `flush` on the buffer. So I just [pushed a commit](https://github.com/manastech/crystal/commit/636531487f32be65cb9c304009ef3fe7f348aa41) doing things correctly: have an intermediate buffer and flush when its full. This avoids useless memory allocations.

The benchmark I'm using for Crystal is this:

```crystal
require "redis"

n = 2_000_000
time = Time.now

Redis.new.pipelined do |pipeline|
  n.times do |i|
    pipeline.set("foo", "bar")
  end
end

elapsed = Time.now - time
puts "Elapsed: #{elapsed}"
puts "Commands per second: #{n.fdiv(elapsed.total_seconds)}"
```

With the BufferedIO optimization I went from ~560000 to ~630000 commands per second. You can try this by checking out the compiler's source code and then doing `/path/to/crystal/bin/crystal benchmark.cr --release`, the `bin/crystal` wrapper will make it use the checked out standard library with the optimization in place.

But in your README it says that Redigo does 640000 commands per second. So I wanted to try it out. The first program I wrote is this:

```go
package main

import "github.com/garyburd/redigo/redis"
import "time"
import "fmt"

func main() {
  c, err := redis.Dial("tcp", ":6379")
  if err != nil {
      // handle error
  }
  defer c.Close()

  startTime := time.Now()
  n := 2000000
  for i := 0; i < n; i++  {
    c.Send("SET", "foo", "bar")
  }
  c.Flush()
  endTime := time.Now()
  seconds := endTime.Sub(startTime).Seconds()
  fmt.Println("Elapsed: ", seconds)
  fmt.Println("Commands per second: ", float64(n) / seconds)
}
```

I get about ~660000 commands per second. What a beast!

However, there's something unfair. Crystal's code does the requests, flushes, and then invokes the same number of "receive" commands. So I changed the Go program to this:

```go
package main

import "github.com/garyburd/redigo/redis"
import "time"
import "fmt"

func main() {
  c, err := redis.Dial("tcp", ":6379")
  if err != nil {
      // handle error
  }
  defer c.Close()

  startTime := time.Now()
  n := 2000000
  for i := 0; i < n; i++  {
    c.Send("SET", "foo", "bar")
  }
  c.Flush()
  for i := 0; i < n; i++  {
    c.Receive()
  }
  endTime := time.Now()
  seconds := endTime.Sub(startTime).Seconds()
  fmt.Println("Elapsed: ", seconds)
  fmt.Println("Commands per second: ", float64(n) / seconds)
}
```

Now I get about ~640000 commands per second, similar to Crystal. This is on a MacBook Pro (Retina, 15-inch, Early 2013).

What benchmarks are you using?

**Comment by stefanwille** [comment]
@asterite Hi Ary!

I use almost the same benchmark as you: 1,000,000 times send `set("foo", "bar")` in pipeline mode. I have published my benchmark code for the various languages in this GitHub repo: https://github.com/stefanwille/redis-client-benchmarks. My plan is to add Node.js and then to write a blog post about the results.

It is so cool that you worked on Crystal std lib to improve the performance compared to Go!! :-))

I tried the new compiler version, but unfortunately I get a segmentation fault when running the crystal-redis spec.  I did a `git bisect` and found that the segfault was introduced by this commit:
```
1572ff4a1f0fffb0ac31515f5ca0e0930a67fc93 - Fixed #547: String#to_i (and related) should
raise on overflow/underflow. Also: implement to_i, to_i64, etc., in pure crystal, and added to_i? 
variants for getting nil on invalid values, as well as a version accepting a block.
```

Sounds rather innocent, but this is what introduced the segfault.

**Comment by kostya** [comment]
maybe add this benchmarks to here https://github.com/kostya/benchmarks

**Comment by asterite** [comment]
@stefanwille I can't reproduce the segfault. `String#to_i` uses pointers so it might have a bug that leads to a segfault.

You can try to print the lines that you are converting with `to_i` and `to_i64` before you get the segfault, that might give us the clue why it's happening.

**Comment by stefanwille** [comment]
@asterite Hello Ary,

I found two things. The first crash is probably more of a side problem.
The second is the one that crashes the crystal-redis spec.


### 1. private method in spec crashes the spec

With this file content in `spec/redis.cr`:

```crystal
require "./spec_helper"

# This crashes only if foo is private
private def foo
end
```

I get this crash:

```crystal
$ crystal spec
Using compiled compiler at .build/crystal
Nil assertion failed
*Exception#initialize<Exception, String, Nil>:Array(String) +21 [4492336661]
*Exception::new<String>:Exception +111 [4492336607]
*raise<String>:NoReturn +6 [4492184566]
*Nil#!<Nil>:Bool +0 [4493068688]
*Crystal::Expressions@Crystal::ASTNode#type<Crystal::Expressions>:Crystal::Type+ +71 [4496648871]
*Crystal::CodeGenVisitor#initialize<Crystal::CodeGenVisitor, Crystal::Program, Crystal::Expressions, (Nil | String | Bool | Array(String)), Bool, LLVM::Module, Bool>:(Nil | LLVM::Value) +290 [4502421490]
*Crystal::CodeGenVisitor::new<Crystal::Program, Crystal::Expressions, (Nil | String | Bool | Array(String)), Bool, LLVM::Module, Bool>:Crystal::CodeGenVisitor +210 [4502421154]
*Crystal::Program#build<Crystal::Program, Crystal::Expressions, (Nil | String | Bool | Array(String)), Bool, LLVM::Module, Bool>:Hash(String, LLVM::Module) +124 [4495468540]
*Crystal::Program#build:debug:single_module:expose_crystal_main<Crystal::Program, Crystal::Expressions, Bool, (Nil | String | Bool | Array(String)), Bool>:Hash(String, LLVM::Module) +119 [4495468407]
*Crystal::Compiler#build<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:(Nil | Bool) +1281 [4492459585]
*Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +523 [4492454235]
*Crystal::Command::run_specs<Array(String)>:Nil +909 [4492442237]
*Crystal::Command::run<Array(String)>:(Nil | CFileIO | File | Bool | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +1475 [4492427267]
*Crystal::Command::run:(Nil | CFileIO | File | Bool | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +37 [4492425701]
__crystal_main +33876 [4492183636]
main +40 [4492185592]

Error: you've found a bug in the Crystal compiler. Please open an issue: https://github.com/manastech/crystal/issues
```



### 2. Instantiating an exception crashes the spec

With this file content in `spec/redis.cr`:

```crystal
Exception.new("hello")
```

I get a crash in `exception.cr` / `Unwind.step(cursor_ptr)`.

The following output is influenced by some `puts` statements that I put into `exception.cr`:

```
$ crystal spec
Using compiled compiler at .build/crystal
* Exception initialize 1
* Exception initialize 2
* Exception initialize 3
* caller 1
* caller 3
* caller 4
* unwind_step 1
* unwind_step 2
* caller 4 while 1
* caller 4 while 2
* caller 4 while 3
* caller 4 while 4
* caller 4 while 5
* caller 4 while 8
* unwind_step 1
* unwind_step 2
* caller 4 while 1
* caller 4 while 2
* caller 4 while 3
* caller 4 while 4
* caller 4 while 5
* caller 4 while 8
* unwind_step 1
* unwind_step 2
* caller 4 while 1
* caller 4 while 2
* caller 4 while 3
* caller 4 while 4
* caller 4 while 5
* caller 4 while 8
* unwind_step 1
Program terminated abnormally with error code: 11
```

The call stack is this:

```
  Exception.new
    Exception#initialize
      caller
        Unwind.step
```

and the crash happens in `Unwind.step`.

To trace this, I have introduced a new funtion `unwind_step`:

```crystal
def unwind_step(cursor_ptr)
  puts "* unwind_step 1"
  s = Unwind.step(cursor_ptr)
  puts "* unwind_step 2"
  s
end
```

I replaced the original call to `Unwind.step` with `unwind_step`.
Therefore I know that it is `Unwind.step` where the program crashes.

Can I give your more information?

**Comment by asterite** [comment]
@stefanwille Hi Stefan,

Thanks for the detailed explanation :-)

The first one was [easy to fix](https://github.com/manastech/crystal/commit/de499b28978d8c8ecf5fc0ce8aa457358e8b249d).

About the second, I suspect it's the same old LLVM bug still lurking around. What LLVM version are you using? Are you on a Mac?

**Comment by stefanwille** [comment]
@asterite

I am on a Mac. I had LLVM 3.5.1 from Homebrew. I just upgraded to Homebrew LLVM 3.6.0 and my second issue went away :smile:

After I pulled the latest Crystal compiler, my benchmark result improved dramatically! Now Crystal is 50% faster than Go... just impressive!!!

**Comment by asterite** [comment]
@stefanwille I'm amazed too!

**Comment by stefanwille** [comment]
@asterite I got the percentage wrong - 685,000 vs 497,000 is 37% better. Still amazing! :smile_cat:

**Pull request merged**
